#!/bin/sh
# Pin system GHC: apt's xmonad libs are not visible to ghcup's GHC.
exec /usr/bin/ghc --make xmonad.hs -i -ilib -main-is main -v0 \
  -outputdir "${XDG_CACHE_HOME:-$HOME/.cache}/xmonad/build-x86_64-linux" -o "$1"
