# install: sudo install -m 644 30-touchpad-tap.conf /etc/X11/xorg.conf.d/
Section "InputClass"
    Identifier "tap-to-click"
    MatchIsTouchpad "on"
    Driver "libinput"
    Option "Tapping" "on"
EndSection
